################################SimParams###########################
dynamics_dt: 0.00001
control_dt: 0.001
use_spring_damper: false
go_home: false


###############################SuspeParams##########################
#Note: all params should be defined at frame on suspension/wheel 0

spring_length: 0.100
spring_kp: 2000.
spring_kd: 200.
spring_range: 0.030
suspe_length0: 0.05168
suspe_length1: 0.10233
suspe_q_offset: -0.32 # Right-handed coordinate

spring_preload: [30.,30.,50.,50.]
###############################ChassisParams##########################
bodyMass: 9.57870388
suspeMass: .66250
wheelMass: .590
rotorMass: .055

bodyLength: 0.58
bodyWidth: 0.52
bodyHeight: 0.015
suspeLinkLength: 0.2
wheelRadius: 0.075
wheelGearRatio: 19

motorTauMax: .15789f # 3508 rotor
batteryV: 24.
motorKT: .0059333   # this is flux linkage * pole pairs
motorR: 0.194
jointDamping: .01
jointDryFriction: .1

#floating point value in table should define with decimal point (0 -> 0.)
bodyRotationalInertia: [0.31567458, 0.00722115, -0.02433380,
                        0.00722115, 0.39576078, -0.00016130,
                        -0.02433380, -0.00016130, 0.26503824]

suspeRotationalInertia: [0.00079435, 0.00002251, 0.00019765,
                         0.00002251, 0.00105859, 0.00001161,
                         0.00019765, 0.00001161, 1.6338e-05]

wheelRotationalInertia: [0.00040756, 0., 0.,
                         0., 0.00078027, 0.,
                         0., 0., 0.00040761]

rotorRotationalInertiaZ: [.000013, 0., 0.,
                          0., .000013, 0.,
                          0., 0., .000023]

suspeLocation: [0.083, -0.17, 0.0075]
wheelLocation: [-0.1118, 0.0514, 0.]
wheelRotorLocation: [-0.1118, 0.0314,0.]
rfidPosLocation: [0,0,-0.0089]

bodyCOM: [-0.02921913,-0.00063774,0.10989947]
suspeCOM: [-0.094554, -0.02185, 0.00938]
wheelCOM: [0.,-0.0169,0.]

