################################SimParams###########################
dynamics_dt: 0.00001
control_dt: 0.001
floor_kp: 5000
floor_kd: 500000
home_kp_lin: 2500
home_kd_lin: 300
home_kp_ang: 250
home_kd_ang: 60
use_spring_damper: false
go_home: false
#floating point value in table should define with decimal point
home_pos: [0.,0.,.5]
home_rpy: [0.,0.,0.]

###############################SuspeParams##########################
#Note: all params should be defined at frame on suspension/wheel 0

spring_length: 0.120
spring_kp: 5.
spring_kd: 1.
spring_range: 0.030
spring_preload: 0.
suspe_length0: 0.05168
suspe_length1: 0.10233
suspe_q_offset: -0.523598 # Right-handed coordinate