################################SimParams###########################
dynamics_dt: 0.00001
control_dt: 0.0001
floor_kp: 5000
floor_kd: 500000
home_kp_lin: 2500
home_kd_lin: 300
home_kp_ang: 250
home_kd_ang: 60
use_spring_damper: false
go_home: false

#floating point value in table should define with decimal point
home_pos: [0.,0.,.5]
home_rpy: [0.,0.,0.]

###############################SuspeParams##########################
#Note: all params should be defined at frame on suspension/wheel 0

spring_length: 0.100
spring_kp: 5000.
spring_kd: 200.
spring_range: 0.030
spring_preload: 0.
suspe_length0: 0.05168
suspe_length1: 0.10233
suspe_q_offset: -0.32 # Right-handed coordinate

###############################ChassisParams##########################
bodyMass: 10.
suspeMass: .66250
wheelMass: .590
rotorMass: .055

bodyLength: 0.58
bodyWidth: 0.52
bodyHeight: 0.1
suspeLinkLength: 0.2
wheelRadius: 0.075
wheelGearRatio: 19

motorTauMax: .15789f # 3508 rotor
batteryV: 24.
motorKT: .0059333   # this is flux linkage * pole pairs
motorR: 0.194
jointDamping: .01
jointDryFriction: .1

#floating point value in table should define with decimal point (0 -> 0.)
bodyRotationalInertia: [0.08376653, 0., 0.,
                        0., 0.10663120, 0.,
                        0., 0., 0.17595299]

suspenRotationalInertia: [0.00079435, 0.00002251, 0.00019765,
                          0.00002251, 0.00105859,  0.00001161,
                          0.00019765, 0.00001161, 1.6338e-05]

wheelRotationalInertia: [0.00040756, 0., 0.,
                         0., 0.00078027, 0.,
                         0., 0., 0.00040761]

rotorRotationalInertiaZ: [.000013, 0., 0.,
                          0., .000013, 0.,
                          0., 0., .000023]

suspeLocation: [0.083, -0.172,-0.025]
wheelLocation: [-0.11135,0.0324,0.]
wheelRotorLocation: [-0.11135,-0.0354,0.]
rfidPosLocation: [0,0,-0.0089]

bodyCOM: [0.,0.,0.00779]
suspeCOM: [-0.094554, -0.02185, 0.00938]
wheelCOM: [0.,-0.0169,0.]

